create table USUARIO
(
ID_USUARIO NUMBER(18),
NOMBRE VARCHAR2(200),
CLAVE VARCHAR2(200),
RUT NUMBER(10),
DV CHAR
);
CREATE SEQUENCE SQ_USUARIO 
MINVALUE 1 START WITH 1 INCREMENT BY 1 
CACHE 10;

INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','ADMIN',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'FULANITO','ADMIN',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'JOSE FELICIANO','ADMIN',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');
INSERT INTO USUARIO VALUES(SQ_USUARIO.NEXTVAL,'NOMBRE','CLAVE',27001001,'K');

SELECT * FROM USUARIO;
COMMIT;
DROP TABLE USUARIO;
DROP SEQUENCE SQ_USUARIO;